My\AppBundle\Entity\CategoryPrice:
    type: entity
    table: category_prices
    repositoryClass: My\AppBundle\Repository\CategoryPriceRepository
    id:
        category:
            associationKey: true
        region:
            associationKey: true
    fields:
        price_edu:
            type: integer
        price_drv:
            type: integer
        price_drv_at:
            type: integer
        active:
            type: boolean
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: categories_prices
        region:
            targetEntity: Region
            inversedBy: categories_prices
