My\AppBundle\Entity\OfferStudent:
    type: entity
    table: offers_students
    repositoryClass: My\AppBundle\Repository\OfferStudentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        subtitle:
            type: string
            nullable: true
        _desc:
            type: text
        description:
            type: text
        started_at:
            type: date
            nullable: true
        ended_at:
            type: date
            nullable: true
        is_public:
            type: boolean
        position:
            type: integer
            gedmo:
                - sortablePosition
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
    oneToOne:
        image:
            targetEntity: Image
            mappedBy: offer_student
            cascade: [ all ]
    oneToMany:
        prices:
            targetEntity: OfferPriceStudent
            mappedBy: offer_student
            cascade: [ all ]
