<?php

namespace My\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferStudentRepository extends EntityRepository
{
    public function getActiveOffers($is_public = null)
    {
        $qb = $this->createQueryBuilder('o')
            ->andWhere('(o.started_at <= :today OR o.started_at IS NULL)')
            ->andWhere('(o.ended_at >= :today OR o.ended_at IS NULL)')
            ->setParameter(':today', new \DateTime('today'))
            ->addOrderBy('o.position', 'ASC')
        ;
        if (!is_null($is_public)) {
            $qb->andWhere('o.is_public = :is_public')->setParameter('is_public', (bool)$is_public);
        }
        return $qb->getQuery()->execute();
    }
}
